// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecjmpcbkarhaasshxyfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjam1wY2JrYXJoYWFzc2h4eWZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MTcwNzIsImV4cCI6MjA3MjQ5MzA3Mn0.j5b0bwD8H7wpYwDJIKY_sVb0tadfuTPzWVYTNfgSwDA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});